Fatal error: exception Failure("Duplicate parameter x in foo")
